# Site settings"
course_name: Basics of Statistical Inference
course_description: "This course is an introduction to the basic concepts and techniques of statistical inference. The course covers the fundamental principles of statistical inference, including estimation, hypothesis testing, and confidence intervals. The course also covers the basics of probability theory, including random variables, probability distributions, and the central limit theorem. The course might use the R programming language for data analysis and statistical computing."
course_semester: "Fall 2024"

# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://basics-of-statistial-inference-fa24.github.io" # the base hostname & protocol for your site

schoolname: Harvard T.H. Chan School of Public Health
schoolurl: "http://www.hsph.harvard.edu"
# twitter_username: 

# address: |
#     School of Witchcraft and Wizardry
#     Hogwarts
#     Scotland

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

exclude:
  - develop

dateformat: "%m/%d/%Y"

timezone: "America/New_York"
future: true
collections:
    events:
        output: true
    lectures:
        output: true
    homeworks:
        output: true
    announcements:
        output: false
    labs:
        output: true


defaults:
  - scope:
      path: ""
      type: "homeworks"
    values:
      layout: "homework"
